# model.py

"""
Core definitions for the app:
- MUSCLES: the muscle groups we track fatigue/recovery for
- EXERCISES: the lifts you log, with primary/secondary muscles +  (stimulus fatigue)
"""

# You can tweak this list anytime.
MUSCLES = [
    "chest",
    "traps",
    "lats",
    "front_delts",
    "side_delts",
    "rear_delts",
    "biceps",
    "triceps",
    "forearm_flexors",
    "forearm_extensors",
    "brachioradialis",
    "quads",
    "hamstrings",
    "glutes",
    "calves",
    "lower_back",
    "abs",
    "neck_flexors",
    "neck_extensors",
]


# Exercise database.
# Key = internal id (no spaces, snake_case).
# SFR = stimulus-to-fatigue ratio (higher = better).

# These are dictionaries, so two variables connected. Exercises are dictionaries
# all in one dicitonary called exercises

EXERCISES = {
    "hang_clean": {
        "name": "Hang Clean",
        "primary": ["glutes", "lower_back"],
        "secondary": ["hamstrings", "front_delts"],
        "tertiary": ["traps", "brachioradialis", "abs"],
        "sfr": 2.0,
    },
    "wrist_curl": {
        "name": "Wrist Curl",
        "primary": ["forearm_flexors"],
        "secondary": [],
        "tertiary": [],
        "sfr": 4.0,
    },
    "reverse_barbell_curl": {
        "name": "Reverse Barbell Curl",
        "primary": ["brachioradialis"],
        "secondary": ["biceps", "forearm_extensors"],
        "tertiary": [],
        "sfr": 3.8,
    },
    "dumbbell_pullover": {
        "name": "Dumbbell Pullover",
        "primary": ["lats", "chest", "triceps"],
        "secondary": [],
        "tertiary": ["abs", "forearm_flexors"],
        "sfr": 3.2,
    },
    "pull_ups": {
        "name": "Pull Ups",
        "primary": ["lats", "traps"],
        "secondary": ["biceps", "brachioradialis"],
        "tertiary": ["abs"],
        "sfr": 3.4,
    },
    "face_pull": {
        "name": "Face Pull",
        "primary": ["rear_delts", "traps"],
        "secondary": ["side_delts"],
        "tertiary": ["brachioradialis"],
        "sfr": 4.0,
    },  
    "incline_dumbbell_bench_press": {
        "name": "Incline Dumbbell Bench Press",
        "primary": ["chest", "front_delts"],
        "secondary": ["triceps"],
        "tertiary": [],
        "sfr": 3.7,
    },
    "kettlebell_swing": {
        "name": "Kettlebell Swing",
        "primary": ["hamstrings", "glutes"],
        "secondary": ["lower_back", "abs"],
        "tertiary": ["traps"],
        "sfr": 2.5,
    },
    "neck_extension": {
        "name": "Neck Extension",
        "primary": ["neck_extensors"],
        "secondary": [],
        "tertiary": [],
        "sfr": 4.0,
    },
    "neck_curl": {
        "name": "Neck Curl",
        "primary": ["neck_flexors"],
        "secondary": [],
        "tertiary": [],
        "sfr": 4.0,
    },
    "bent_over_row": {
        "name": "Bent Over Row",
        "primary": ["traps"],
        "secondary": ["lats", "rear_delts", "biceps", "brachioradialis"],
        "tertiary": ["lower_back"],
        "sfr": 3.2,
    },
    "shoulder_press": {
        "name": "Shoulder Press",
        "primary": ["front_delts", "side_delts"],
        "secondary": ["triceps", "traps"],
        "tertiary": [],
        "sfr": 3.3,
    },
    "back_extension": {
        "name": "Back Extension",
        "primary": ["lower_back"],
        "secondary": ["glutes", "hamstrings"],
        "tertiary": [],
        "sfr": 3.2,
    },
    "dumbbell_lateral_raise": {
        "name": "Dumbbell Lateral Raise",
        "primary": ["side_delts"],
        "secondary": ["traps"],
        "tertiary": ["front_delts"],
        "sfr": 4.5,
    },
    "leg_extension": {
        "name": "Leg Extension",
        "primary": ["quads"],
        "secondary": [],
        "tertiary": [],
        "sfr": 4,
    },
    "treadmill_run": {
        "name": "Treadmill Run",
        "primary": ["quads", "hamstrings", "calves"],
        "secondary": ["glutes"],
        "tertiary": ["abs", "lower_back"],
        "sfr": 1.5,
    },
    "reverse_wrist_curl": {
        "name": "Reverse Wrist Curl",
        "primary": ["forearm_extensors"],
        "secondary": [],
        "tertiary": [],
        "sfr": 3.8,
    },
    "nordic_hamstring_curl": {
        "name": "Nordic Hamstring Curl",
        "primary": ["hamstrings"],
        "secondary": ["glutes"],
        "tertiary": ["lower_back"],
        "sfr": 3.8,
    },
    "sled_leg_press": {
        "name": "Sled Leg Press",
        "primary": ["quads", "glutes"],
        "secondary": ["hamstrings"],
        "tertiary": [],
        "sfr": 4.0,
    },
    "mace_swings": {
        "name": "Mace Swings",
        "primary": ["triceps", "front_delts"],
        "secondary": ["abs", "forearm_flexors", "brachioradialis"],
        "tertiary": ["traps", "side_delts"],
        "sfr": 2.5,
    },
    "forearm_riser": {
        "name": "Forearm Riser",
        "primary": ["forearm_extensors"],
        "secondary": [],
        "tertiary": [],
        "sfr": 3.8,
    },
    "forearm_riser_reverse": {
        "name": "Forearm Riser Reverse",
        "primary": ["forearm_flexors"],
        "secondary": [],
        "tertiary": [],
        "sfr": 3.8,
    },
    "forearm_pronations_rope": {
        "name": "Forearm Pronations Rope",
        "primary": ["forearm_flexors"],
        "secondary": [],
        "tertiary": [],
        "sfr": 3.8,
    },
    "bench_press": {
        "name": "Bench Press",
        "primary": ["chest"],
        "secondary": ["triceps", "front_delts"],
        "tertiary": [],
        "sfr": 3.5,
    },
    "incline_dumbbell_curl": {
        "name": "Incline Dumbbell Curl",
        "primary": ["biceps"],
        "secondary": [],
        "tertiary": ["forearm_flexors"],
        "sfr": 4.3,
    },
    "squat": {
        "name": "Squat",
        "primary": ["quads", "glutes"],
        "secondary": ["lower_back"],
        "tertiary": [],
        "sfr": 3.0,
    },
    "cable_bicep_curl": {
        "name": "Cable Bicep Curl",
        "primary": ["biceps"],
        "secondary": ["forearm_flexors"],
        "tertiary": [],
        "sfr": 4.3,
    },
    "pseudo_planche_push_up": {
        "name": "Pseudo Planche Push Up",
        "primary": ["chest", "front_delts"],
        "secondary": ["triceps"],
        "tertiary": [],
        "sfr": 3.0,
    },
    "rear_pec_fly_with_expander": {
        "name": "Rear Pec Fly with Expander",
        "primary": ["rear_delts", "traps"],
        "secondary": [],
        "tertiary": [],
        "sfr": 4.0,
    },
    "deadlift": {
        "name": "Deadlift",
        "primary": ["hamstrings", "glutes", "lower_back"],
        "secondary": ["traps"],
        "tertiary": ["quads"],
        "sfr": 2.0,
    },
    "dumbbell_fly": {
        "name": "Dumbbell Fly",
        "primary": ["chest"],
        "secondary": [],
        "tertiary": ["front_delts"],
        "sfr": 3.5,
    },
    "one_arm_pull_ups": {
        "name": "One Arm Pull Ups",
        "primary": ["lats", "traps"],
        "secondary": ["biceps", "brachioradialis", "forearm_flexors"],
        "tertiary": ["rear_delts", "abs"],
        "sfr": 2.8,
    },
    "incline_dumbbell_fly": {
        "name": "Incline Dumbbell Fly",
        "primary": ["chest"],
        "secondary": ["front_delts"],
        "tertiary": [],
        "sfr": 3.4,
    },
    "hammer_curl": {
        "name": "Hammer Curl",
        "primary": ["brachioradialis"],
        "secondary": [],
        "tertiary": ["biceps"],
        "sfr": 4.2,
    },
    "paused_bench_press": {
        "name": "Paused Bench Press",
        "primary": ["chest"],
        "secondary": ["triceps", "front_delts"],
        "tertiary": [],
        "sfr": 3.3,
    },
    "alternating_kettlebell_hang_clean": {
        "name": "Alternating Kettlebell Hang Clean",
        "primary": ["glutes", "lower_back"],
        "secondary": ["hamstrings", "front_delts"],
        "tertiary": ["traps", "forearm_flexors", "abs"],
        "sfr": 2.3,
    },
    "dumbbell_shoulder_press": {
        "name": "Dumbbell Shoulder Press",
        "primary": ["front_delts"],
        "secondary": ["side_delts", "triceps"],
        "tertiary": [],
        "sfr": 3.5,
    },
    "back_press": {
        "name": "Back Press",
        "primary": ["side_delts", "triceps"],
        "secondary": [],
        "tertiary": [],
        "sfr": 3.0,
    },
    "seated_cable_row": {
        "name": "Seated Cable Row",
        "primary": ["traps"],
        "secondary": ["lats", "rear_delts", "biceps", "brachioradialis"],
        "tertiary": [],
        "sfr": 3.8,
    },
    "overhead_pullapart_pronated": {
        "name": "Overhead Pullapart (Pronated)",
        "primary": ["rear_delts", "traps"],
        "secondary": [],
        "tertiary": ["triceps"],
        "sfr": 4.0,
    },
    "incline_bench_press": {
        "name": "Incline Bench Press",
        "primary": ["chest", "front_delts"],
        "secondary": ["triceps"],
        "tertiary": [],
        "sfr": 3.5,
    },
    "lat_pulldown": {
        "name": "Lat Pulldown",
        "primary": ["lats"],
        "secondary": ["biceps", "rear_delts", "brachioradialis"],
        "tertiary": ["forearm_flexors"],
        "sfr": 3.8,
    },
    "dips": {
        "name": "Dips",
        "primary": ["triceps", "chest"],
        "secondary": ["front_delts"],
        "tertiary": [],
        "sfr": 3.2,
    },
    "seated_dumbbell_shoulder_press": {
        "name": "Seated Dumbbell Shoulder Press",
        "primary": ["front_delts"],
        "secondary": ["side_delts", "triceps"],
        "tertiary": [],
        "sfr": 3.6,
    },
    "romanian_deadlift": {
        "name": "Romanian Deadlift",
        "primary": ["hamstrings", "glutes"],
        "secondary": ["lower_back"],
        "tertiary": [],
        "sfr": 2.5,
    },
    "bicep_curl": {
        "name": "Dumbbell Bicep Curl",
        "primary": ["biceps"],
        "secondary": [],
        "tertiary": ["forearm_flexors"],
        "sfr": 4.5,
    },
    "tricep_pushdown": {
        "name": "Cable Tricep Pushdown",
        "primary": ["triceps"],
        "secondary": [],
        "tertiary": [],
        "sfr": 4.0,
    },
    "leg_press": {
        "name": "Leg Press",
        "primary": ["quads"],
        "secondary": ["glutes"],
        "tertiary": [],
        "sfr": 4.0,
    },
    "leg_curl": {
        "name": "Leg Curl",
        "primary": ["hamstrings"],
        "secondary": [],
        "tertiary": [],
        "sfr": 4.0,
    },
    "calf_raise": {
        "name": "Standing Calf Raise",
        "primary": ["calves"],
        "secondary": [],
        "tertiary": [],
        "sfr": 4.0,
    },
}
